"""initial schema

Revision ID: ea7c264e0c95
Revises: 
Create Date: 2026-08-26 02:22:24.345929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7c264e0c95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scans',
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scan_paths', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('files_discovered', sa.Integer(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('pii_findings', sa.Integer(), nullable=False),
    sa.Column('secret_findings', sa.Integer(), nullable=False),
    sa.Column('severity_counts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('scan_id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('risk_severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('ix_files_scan_id', ['scan_id'], unique=False)
        batch_op.create_index('ix_files_sha256', ['sha256'], unique=False)

    op.create_table('findings',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('endpoint_id', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=False),
    sa.Column('redacted_evidence', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('finding_id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index('ix_findings_category', ['category'], unique=False)
        batch_op.create_index('ix_findings_scan_id', ['scan_id'], unique=False)
        batch_op.create_index('ix_findings_severity', ['severity'], unique=False)
        batch_op.create_index('ix_findings_status', ['status'], unique=False)

    op.create_table('scan_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_errors', schema=None) as batch_op:
        batch_op.create_index('ix_scan_errors_scan_id', ['scan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_errors', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_errors_scan_id')

    op.drop_table('scan_errors')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index('ix_findings_status')
        batch_op.drop_index('ix_findings_severity')
        batch_op.drop_index('ix_findings_scan_id')
        batch_op.drop_index('ix_findings_category')

    op.drop_table('findings')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_sha256')
        batch_op.drop_index('ix_files_scan_id')

    op.drop_table('files')
    op.drop_table('scans')
    op.drop_table('policies')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
