"""initial schema

Revision ID: df4dec01519b
Revises: 
Create Date: 2026-08-26 02:43:19.421347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datasentinel_backend.core.types


# revision identifiers, used by Alembic.
revision: str = 'df4dec01519b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_org_id', 'audit_logs', ['org_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('hashed_api_token', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'hostname', name='uq_endpoint_org_hostname')
    )
    op.create_index('ix_endpoints_org_id', 'endpoints', ['org_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_policy_org_name')
    )
    op.create_index('ix_policies_org_id', 'policies', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_org_id', 'users', ['org_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('endpoint_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scan_paths', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('files_discovered', sa.Integer(), nullable=False),
    sa.Column('files_scanned', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('pii_findings', sa.Integer(), nullable=False),
    sa.Column('secret_findings', sa.Integer(), nullable=False),
    sa.Column('severity_counts', sa.JSON(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scans_endpoint_id', 'scans', ['endpoint_id'], unique=False)
    op.create_index('ix_scans_org_id', 'scans', ['org_id'], unique=False)
    op.create_table('files',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('scan_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('risk_severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_scan_id', 'files', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('org_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('endpoint_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('scan_id', datasentinel_backend.core.types.GUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=False),
    sa.Column('redacted_evidence', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_category', 'findings', ['category'], unique=False)
    op.create_index('ix_findings_endpoint_id', 'findings', ['endpoint_id'], unique=False)
    op.create_index('ix_findings_org_id', 'findings', ['org_id'], unique=False)
    op.create_index('ix_findings_scan_id', 'findings', ['scan_id'], unique=False)
    op.create_index('ix_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('ix_findings_status', 'findings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_findings_status', table_name='findings')
    op.drop_index('ix_findings_severity', table_name='findings')
    op.drop_index('ix_findings_scan_id', table_name='findings')
    op.drop_index('ix_findings_org_id', table_name='findings')
    op.drop_index('ix_findings_endpoint_id', table_name='findings')
    op.drop_index('ix_findings_category', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_files_scan_id', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_scans_org_id', table_name='scans')
    op.drop_index('ix_scans_endpoint_id', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_users_org_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_policies_org_id', table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_endpoints_org_id', table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index('ix_audit_logs_org_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('organizations')
    # ### end Alembic commands ###
